# Qualitative Evaluation

This notebook performs qualitative evaluation (coverage, diversity, novelty, serendipity) for four recommendation methods: Most Popular, SVD, BPR, and GRU4Rec, across all datasets.

In [ ]:
!pip install recommenders==1.2.1

## Preparation

In [2]:
import pickle
import pandas as pd


from recommenders.evaluation.python_evaluation import (
    catalog_coverage,
    diversity,
    novelty,
    serendipity,

)

import warnings
warnings.filterwarnings('ignore')

## Animelist

Run evaluation for animelist dataset

In [5]:
import pickle

In [1]:
DATA_PATH = 'dataset/animelist/data_sample_split/'

In [3]:
train_data = pd.read_csv(f'{DATA_PATH}/data_train_full.tsv', sep='\t')
test_data = pd.read_csv(f'{DATA_PATH}/data_test.tsv', sep='\t')

In [ ]:
PREDICTION_PATH = DATA_PATH + 'predictions'
all_predictions_svd = pickle.load(open(f'{PREDICTION_PATH}/predictions_svd_opt.pkl', 'rb'))
all_predictions_mpop = pickle.load(open(f'{PREDICTION_PATH}/predictions_pop_opt.pkl', 'rb'))
all_predictions_bpr = pickle.load(open(f'{PREDICTION_PATH}/predictions_bpr_opt.pkl', 'rb'))
all_predictions_gru =  pickle.load(open(f'{PREDICTION_PATH}/predictions_gru_opt.pkl', 'rb'))

In [34]:
all_predictions_svd = all_predictions_svd.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_mpop = all_predictions_mpop.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_bpr = all_predictions_bpr.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_gru = all_predictions_gru.sort_values(by=['user_id', 'prediction'], ascending=[True, False])

In [35]:
top10_svd = all_predictions_svd.groupby('user_id').head(10).reset_index(drop=True)
top10_mpop = all_predictions_mpop.groupby('user_id').head(10).reset_index(drop=True)
top10_bpr = all_predictions_bpr.groupby('user_id').head(10).reset_index(drop=True)

In [36]:
top10_mpop['user_id'] = top10_mpop['user_id'].astype(int)
top10_mpop['anime_id'] = top10_mpop['anime_id'].astype(int)

In [37]:
filtered_df_gru = all_predictions_gru.merge(train_data, on=['user_id', 'anime_id'], how='left', indicator=True)
filtered_df_gru = filtered_df_gru[filtered_df_gru['_merge'] == 'left_only']
filtered_df_gru = filtered_df_gru.drop(columns=['_merge'])

In [ ]:
len(all_predictions_gru), len(filtered_df_gru)

(10000000, 9014030)

In [ ]:
len(all_predictions_gru) - len(train_data)

9014030

In [38]:
top10_gru = filtered_df_gru.groupby('user_id').head(10).reset_index(drop=True)

In [39]:
animelist_svd_eval = {
    'coverage': catalog_coverage(train_data, top10_svd, col_user="user_id", col_item="anime_id"),
    'diversity': diversity(train_data, top10_svd, col_user="user_id", col_item="anime_id"),
    'novelty': novelty(train_data, top10_svd, col_user="user_id", col_item="anime_id"),
    'serendipity': serendipity(train_data, top10_svd, col_user="user_id", col_item="anime_id")
}

In [40]:
animelist_mpop_eval = {
    'coverage': catalog_coverage(train_data, top10_mpop, col_user="user_id", col_item="anime_id"),
    'diversity': diversity(train_data, top10_mpop, col_user="user_id", col_item="anime_id"),
    'novelty': novelty(train_data, top10_mpop, col_user="user_id", col_item="anime_id"),
    'serendipity': serendipity(train_data, top10_mpop, col_user="user_id", col_item="anime_id")
}

In [41]:
animelist_bpr_eval = {
    'coverage': catalog_coverage(train_data, top10_bpr, col_user="user_id", col_item="anime_id"),
    'diversity': diversity(train_data, top10_bpr, col_user="user_id", col_item="anime_id"),
    'novelty': novelty(train_data, top10_bpr, col_user="user_id", col_item="anime_id"),
    'serendipity': serendipity(train_data, top10_bpr, col_user="user_id", col_item="anime_id")
}

In [42]:
animelist_gru_eval = {
    'coverage': catalog_coverage(train_data, top10_gru, col_user="user_id", col_item="anime_id"),
    'diversity': diversity(train_data, top10_gru, col_user="user_id", col_item="anime_id"),
    'novelty': novelty(train_data, top10_gru, col_user="user_id", col_item="anime_id"),
    'serendipity': serendipity(train_data, top10_gru, col_user="user_id", col_item="anime_id")
}

In [ ]:
pd.DataFrame({"SVD":animelist_svd_eval,
              "BPR":animelist_bpr_eval,
              "Mpop": animelist_mpop_eval,
              'GRU': animelist_gru_eval})

                   SVD       BPR      Mpop        GRU
coverage      0.431000  0.987000  0.088000   1.000000
diversity     0.766709  0.657023  0.519887   0.670220
novelty      10.112966  9.157680  8.019348  10.373932
serendipity   0.815348  0.709147  0.707451   0.810791

## Goodbooks

Run evaluation for goodbooks dataset

In [8]:
DATA_PATH = 'dataset/goodbooks-10k/data_sample_split/'

In [9]:
train_data = pd.read_csv(f'{DATA_PATH}/data_train_full.tsv', sep='\t')
test_data = pd.read_csv(f'{DATA_PATH}/data_test.tsv', sep='\t')

In [ ]:
PREDICTION_PATH = DATA_PATH + 'predictions'
all_predictions_svd = pickle.load(open(f'{PREDICTION_PATH}/predictions_svd_opt.pkl', 'rb'))
all_predictions_mpop = pickle.load(open(f'{PREDICTION_PATH}/predictions_pop_opt.pkl', 'rb'))
all_predictions_bpr = pickle.load(open(f'{PREDICTION_PATH}/predictions_bpr_opt.pkl', 'rb'))
all_predictions_gru =  pickle.load(open(f'{PREDICTION_PATH}/predictions_gru_opt.pkl', 'rb'))

In [55]:
all_predictions_svd = all_predictions_svd.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_mpop = all_predictions_mpop.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_bpr = all_predictions_bpr.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_gru = all_predictions_gru.sort_values(by=['user_id', 'prediction'], ascending=[True, False])

In [59]:
top10_svd = all_predictions_svd.groupby('user_id').head(10).reset_index(drop=True)
top10_mpop = all_predictions_mpop.groupby('user_id').head(10).reset_index(drop=True)
top10_bpr = all_predictions_bpr.groupby('user_id').head(10).reset_index(drop=True)

In [60]:
top10_mpop['user_id'] = top10_mpop['user_id'].astype(int)
top10_mpop['book_id'] = top10_mpop['book_id'].astype(int)

In [61]:
filtered_df_gru = all_predictions_gru.merge(train_data, on=['user_id', 'book_id'], how='left', indicator=True)
filtered_df_gru = filtered_df_gru[filtered_df_gru['_merge'] == 'left_only']
filtered_df_gru = filtered_df_gru.drop(columns=['_merge'])

In [ ]:
len(all_predictions_gru), len(filtered_df_gru)

(10000000, 9537370)

In [ ]:
len(all_predictions_gru) - len(train_data)

9537370

In [62]:
top10_gru = filtered_df_gru.groupby('user_id').head(10).reset_index(drop=True)

In [63]:
goodbooks_svd_eval = {
    'coverage': catalog_coverage(train_data, top10_svd, col_user="user_id", col_item="book_id"),
    'diversity': diversity(train_data, top10_svd, col_user="user_id", col_item="book_id"),
    'novelty': novelty(train_data, top10_svd, col_user="user_id", col_item="book_id"),
    'serendipity': serendipity(train_data, top10_svd, col_user="user_id", col_item="book_id")
}

In [64]:
goodbooks_mpop_eval = {
    'coverage': catalog_coverage(train_data, top10_mpop, col_user="user_id", col_item="book_id"),
    'diversity': diversity(train_data, top10_mpop, col_user="user_id", col_item="book_id"),
    'novelty': novelty(train_data, top10_mpop, col_user="user_id", col_item="book_id"),
    'serendipity': serendipity(train_data, top10_mpop, col_user="user_id", col_item="book_id")
}

In [65]:
goodbooks_bpr_eval = {
    'coverage': catalog_coverage(train_data, top10_bpr, col_user="user_id", col_item="book_id"),
    'diversity': diversity(train_data, top10_bpr, col_user="user_id", col_item="book_id"),
    'novelty': novelty(train_data, top10_bpr, col_user="user_id", col_item="book_id"),
    'serendipity': serendipity(train_data, top10_bpr, col_user="user_id", col_item="book_id")
}

In [66]:
goodbooks_gru_eval = {
    'coverage': catalog_coverage(train_data, top10_gru, col_user="user_id", col_item="book_id"),
    'diversity': diversity(train_data, top10_gru, col_user="user_id", col_item="book_id"),
    'novelty': novelty(train_data, top10_gru, col_user="user_id", col_item="book_id"),
    'serendipity': serendipity(train_data, top10_gru, col_user="user_id", col_item="book_id")
}

In [ ]:
pd.DataFrame({"SVD":goodbooks_svd_eval,
              "BPR":goodbooks_bpr_eval,
              "Mpop": goodbooks_mpop_eval,
              'GRU': goodbooks_gru_eval})

                  SVD       BPR      Mpop        GRU
coverage     0.608000  0.996000  0.049000   0.990000
diversity    0.871818  0.845919  0.536410   0.783910
novelty      9.411718  9.401073  7.401752  10.168314
serendipity  0.911065  0.859970  0.837119   0.915841

## MovieLens

Run evaluation for goodbooks dataset

In [11]:
DATA_PATH = 'dataset/ml-1m/data_split/'

In [12]:
train_data = pd.read_csv(f'{DATA_PATH}/data_train_full.tsv', sep='\t')
test_data = pd.read_csv(f'{DATA_PATH}/data_test.tsv', sep='\t')

In [ ]:
PREDICTION_PATH = DATA_PATH + 'predictions'
all_predictions_svd = pickle.load(open(f'{PREDICTION_PATH}/predictions_svd_opt.pkl', 'rb'))
all_predictions_mpop = pickle.load(open(f'{PREDICTION_PATH}/predictions_pop_opt.pkl', 'rb'))
all_predictions_bpr = pickle.load(open(f'{PREDICTION_PATH}/predictions_bpr_opt.pkl', 'rb'))
all_predictions_gru =  pickle.load(open(f'{PREDICTION_PATH}/predictions_gru_opt.pkl', 'rb'))

In [71]:
all_predictions_svd = all_predictions_svd.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_mpop = all_predictions_mpop.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_bpr = all_predictions_bpr.sort_values(by=['user_id', 'prediction'], ascending=[True, False])
all_predictions_gru = all_predictions_gru.sort_values(by=['user_id', 'prediction'], ascending=[True, False])

In [72]:
top10_svd = all_predictions_svd.groupby('user_id').head(10).reset_index(drop=True)
top10_mpop = all_predictions_mpop.groupby('user_id').head(10).reset_index(drop=True)
top10_bpr = all_predictions_bpr.groupby('user_id').head(10).reset_index(drop=True)

In [73]:
top10_mpop['user_id'] = top10_mpop['user_id'].astype(int)
top10_mpop['movie_id'] = top10_mpop['movie_id'].astype(int)

In [74]:
filtered_df_gru = all_predictions_gru.merge(train_data, on=['user_id', 'movie_id'], how='left', indicator=True)
filtered_df_gru = filtered_df_gru[filtered_df_gru['_merge'] == 'left_only']
filtered_df_gru = filtered_df_gru.drop(columns=['_merge'])

In [ ]:
len(all_predictions_gru), len(filtered_df_gru)

(20551105, 19885710)

In [ ]:
len(all_predictions_gru) - len(train_data)

19885710

In [75]:
top10_gru = filtered_df_gru.groupby('user_id').head(10).reset_index(drop=True)

In [76]:
movielens_svd_eval = {
    'coverage': catalog_coverage(train_data, top10_svd, col_user="user_id", col_item="movie_id"),
    'diversity': diversity(train_data, top10_svd, col_user="user_id", col_item="movie_id"),
    'novelty': novelty(train_data, top10_svd, col_user="user_id", col_item="movie_id"),
    'serendipity': serendipity(train_data, top10_svd, col_user="user_id", col_item="movie_id")
}

In [77]:
movielens_mpop_eval = {
    'coverage': catalog_coverage(train_data, top10_mpop, col_user="user_id", col_item="movie_id"),
    'diversity': diversity(train_data, top10_mpop, col_user="user_id", col_item="movie_id"),
    'novelty': novelty(train_data, top10_mpop, col_user="user_id", col_item="movie_id"),
    'serendipity': serendipity(train_data, top10_mpop, col_user="user_id", col_item="movie_id")
}

In [78]:
movielens_bpr_eval = {
    'coverage': catalog_coverage(train_data, top10_bpr, col_user="user_id", col_item="movie_id"),
    'diversity': diversity(train_data, top10_bpr, col_user="user_id", col_item="movie_id"),
    'novelty': novelty(train_data, top10_bpr, col_user="user_id", col_item="movie_id"),
    'serendipity': serendipity(train_data, top10_bpr, col_user="user_id", col_item="movie_id")
}

In [79]:
movielens_gru_eval = {
    'coverage': catalog_coverage(train_data, top10_gru, col_user="user_id", col_item="movie_id"),
    'diversity': diversity(train_data, top10_gru, col_user="user_id", col_item="movie_id"),
    'novelty': novelty(train_data, top10_gru, col_user="user_id", col_item="movie_id"),
    'serendipity': serendipity(train_data, top10_gru, col_user="user_id", col_item="movie_id")
}

In [ ]:
pd.DataFrame({"SVD":movielens_svd_eval,
              "BPR":movielens_bpr_eval,
              "Mpop": movielens_mpop_eval,
              'GRU': movielens_gru_eval})

                   SVD       BPR      Mpop        GRU
coverage      0.148978  0.308317  0.030524   0.566508
diversity     0.721235  0.631233  0.469389   0.714547
novelty      10.039740  9.380321  8.264081  10.806049
serendipity   0.791191  0.717743  0.704841   0.804573